//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerListView
    {
        public int QuestionId { get; set; }
        public int QuestionIndex { get; set; }
        public string QuestionText { get; set; }
        public string QuestionType { get; set; }
        public bool AnswerChecked { get; set; }
        public string AnswerText { get; set; }
        public int PatientFormId { get; set; }
    }
}
