//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PTEFEntities : DbContext
    {
        public PTEFEntities()
            : base("name=PTEFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<FormType> FormTypes { get; set; }
        public virtual DbSet<PatientForm> PatientForms { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<PatientListView> PatientListViews { get; set; }
        public virtual DbSet<AnswerListView> AnswerListViews { get; set; }
    }
}
